"""Conservative red-flag checks used around the text classifier."""

CRITICAL_PHRASES = {
    "chest pain",
    "severe chest pain",
    "crushing chest pain",
    "chest pressure spreading",
    "chest pain spreading",
    "difficulty breathing",
    "difficulty breathing at rest",
    "severe difficulty breathing",
    "cannot breathe",
    "can't breathe",
    "cant breathe",
    "unable to breathe",
    "choking and unable to breathe",
    "blue lips",
    "heavy bleeding that will not stop",
    "bleeding heavily",
    "will not stop bleeding",
    "uncontrolled bleeding",
    "severe bleeding",
    "blood spurting",
    "loss of consciousness",
    "unconscious",
    "unresponsive",
    "possible stroke",
    "face drooping",
    "weakness in one arm",
    "one-sided weakness",
    "difficulty speaking",
    "unable to speak",
    "a seizure",
    "seizure that has continued",
    "several seizures",
    "coughing up blood",
    "vomiting blood",
    "throat swelling",
    "tongue swelling",
    "severe allergic reaction",
    "suspected overdose",
    "medication overdose",
    "unknown substance",
    "suicide with an immediate plan",
    "thoughts of suicide with an immediate plan",
    "sudden loss of vision",
    "severe head injury",
    "stiff neck and confusion",
}


def critical_red_flag(text: str) -> bool:
    lowered = text.lower()
    return any(phrase in lowered for phrase in CRITICAL_PHRASES)
